### ISSUE TITLE
Please add Wireguard support for the Linux client

### ISSUE THREAD

**Issue by d4f5409d** [ProtonVPN/linux-app#55] opened 2021-11-05 07:52 UTC
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Please support the Wireguard protocoll on Linux too, not only OpenVPN.

**Comment by uranuspucksaxophone** [comment] 2021-11-14 11:45
Duplicate of #40

**Closed** 2021-11-23 17:38 UTC
