### ISSUE TITLE
Unable to use ProtonVPN on Manjaro Gnome

### ISSUE THREAD

**Issue by tbrimbo** [ProtonVPN/linux-app#18] opened 2021-06-29 10:25 UTC
I am unable to use Protonvpn app or protonvpn-cli on Manjaro Gnome. 
App doesn't launch at all. 
'protonvpn-cli login tbrimbo' and 'protonvpn-cli s' commands both prompt:

Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==3.7.1', 'console_scripts', 'protonvpn-cli')())
  File "/usr/bin/protonvpn-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

I tried them on Manjaro Cinnamon and they work.

**Comment by tbrimbo** [comment] 2021-06-29 10:41
UPDATE: I managed to launch the app. Apparently 'protonvpn' command was linked to '.local/bin/protonvpn' left from uninstalled protonvpn-cli-community. Therefore app wasn't able to use 'protonvpn' command. I deleted the .local/bin/protonvpn and it now launches through taskbar icon and terminal.

protonvpn-cli commands still prompt the same error.

**Comment by tbrimbo** [comment] 2021-06-29 16:26
UPDATE: After a shutdown and start of the computer, Manjaro Gnome is unable to connect to internet. I signed out from Protonvpn app and restarted, still no connection. Shutdown was also stuck. I had  to manually restart. I tried Manjaro Cinnamon and there was internet. I restored a version of Gnome without Protonvpn app, connection is also restored.

**Comment by calexandru2018** [comment] 2021-06-29 16:32
Hey @tbrimbo 

The stopiteration issue happens usually when you incorrectly remove a packge. The rule is:
- If you install via package manager then uninstall it via package manager
- If you install via pip then uninstall it via pip also

What you should do is remove all protonvpn package, be it via pip or package manager. Also make sure (with `which`) that no executable are left behind.

If shutdown/reboot your laptop **without** disconnecting from VPN first then the interface ipv6 interface will be left behind, which will hinder you from reconnecting to internet. Same happens if you enable Kill Switch. 

Regarding the Gnome/Cinnamon situation, I'm myself running on latest Manjaro with Gnome + kernel 5.12 and have no issue, so unless you have a specific/tweaked DE it should be working fine.

**Comment by tbrimbo** [comment] 2021-06-29 16:35
Thanks for the reply. I'll try your advice. Let's see if I can make it work.

**Comment by tbrimbo** [comment] 2021-06-29 17:15
I disconnected from VPN and I am able to connect to internet again. I have to get used to this, it wasn't an issue with linux-cli.

Before I installed the app, I uninstalled protonvpn-cli as described [here](https://github.com/ProtonVPN/linux-cli-community/blob/master/USAGE.md#protonvpn-cli-usage-documentation), since it was installed via pip. Checked again using "which protonvpn" and "which protonvpn-cli" commands but StopIteration issue remains. 

At least it works with the app.

**Comment by parrotx-proton** [comment] 2021-07-01 05:50
@calexandru2018 do you have a documented solution or script for this?

> If you shutdown/reboot your laptop without disconnecting from VPN first then the ipv6 interface will be left behind, which will hinder you from reconnecting to internet. Same happens if you enable Kill Switch.

**Comment by calexandru2018** [comment] 2021-07-01 08:45
@parrotx-proton not it's not documented and there is notscript. Although I've been trying to accomplish this, by implementing inhibitors to systemd (still working on it though).

**Comment by tbrimbo** [comment] 2021-07-03 23:44
>  If you shutdown/reboot your laptop **without** disconnecting from VPN first then the ipv6 interface will be left behind, which will hinder you from reconnecting to internet. Same happens if you enable Kill Switch.

@calexandru2018 I just found out, internet connection is immediately restored if I log out from the app.

**Comment by calexandru2018** [comment] 2021-07-22 08:23
I'm closing this as it somehow duplicate of #20

**Comment by tbrimbo** [comment] 2021-07-22 18:29
GUI works now and I know how to deal with internet connection issue. The only reason I left it open is because I still cannot use protonvpn-cli and get the same stopiteration issue. I followed the instructions above but always same. 

I see someone else had the exact same stopiteration message at [linux-cli #20](https://github.com/ProtonVPN/linux-cli/issues/20) and were given the same advice. Their OS is also Manjaro. They didn't confirm their issue being resolved.

If you think it doesn't contribute anymore, by all means close it.

**Comment by tbrimbo** [comment] 2022-01-15 00:19
Issue seems to be resolved. Closing this. Thanks.

**Closed** 2022-01-15 00:19 UTC
