### ISSUE TITLE
Minimize, Maximize and Close buttons are not displayed

### ISSUE THREAD

**Issue by ig-perez** [ProtonVPN/linux-app#29] opened 2021-07-22 02:56 UTC
Hi, thanks for making a GUI app for Linux. It works fine for me but I can't see the icons on the top right corner. Perhaps it is because I'm under Wayland.

![image](https://user-images.githubusercontent.com/33359427/126583922-c26344f9-f783-421f-9699-aebe255f0c4a.png)

My distro is Fedora 33.

Thanks!

**Comment by calexandru2018** [comment] 2021-07-22 08:08
Closing as this is duplicate of #16

**Closed by calexandru2018** 2021-07-22 08:08 UTC
