### ISSUE TITLE
Dummy connection (pvpn-ipv6leak-protection) alive at boot Linux Mint

### ISSUE THREAD

**Issue by Krusty27** [ProtonVPN/linux-app#23] opened 2021-07-11 12:14 UTC
When I start my PC Wi-Fi connection doesn't work at all and ProtonVPN GUI is stack at loading the first page. If I open Network Settings and disable an interface called "Dummy" Wi-Fi starts working and I can connect to PVPN.

Connection name is: _pvpn-ipv6leak-protection_
Operating system: Linux Mint 20.2 (but also on 20.1) Cinnamon
Linux Kernel: 5.4.0-77-generic

Let me know if you need any log

**Comment by OMGChase** [comment] 2021-07-12 15:06
Hello.

Was about to submit his issue today but saw this pop up.
Experiencing same issue. Dummy connection not killed when exiting ProtonVPN, and when rebooting the machine, internet connection does not work while the dummy connection is active.

**Comment by calexandru2018** [comment] 2021-07-12 15:26
Duplicate of #20

**Closed by calexandru2018** 2021-07-12 15:26 UTC
